name: Full CI/CD Pipeline (Test on Ubuntu, Deploy via SSH)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- PART 1: TEST JOB (Runs on GitHub's Ubuntu Runner) ---
  test_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
        
      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 3. Install Pytest
        run: pip install pytest
          
      - name: 4. Run tests with Pytest
        run: pytest

  # --- PART 2: DEPLOY JOB (Runs only if tests pass) ---
  deploy_job:
    # This job only starts if the 'test_job' completed successfully
    needs: test_job
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Remote Ubuntu Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          # These values are read securely from your GitHub Secrets
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # --- CUSTOMIZE THIS SCRIPT FOR YOUR SERVER ---
          script: |
            echo "Starting deployment on remote Ubuntu server..."
            
            # 1. Navigate to your application directory
            # REPLACE /var/www/my-app-path with your actual path
            cd /var/www/my-app-path
            
            # 2. Pull the latest code from your repository
            git pull origin main
            
            # 3. Reinstall dependencies (if needed)
            /usr/bin/python3 -m pip install -r requirements.txt
            
            # 4. Restart your application service
            # REPLACE your-app-service-name with the actual systemd service name
            sudo systemctl restart your-app-service-name
            
            echo "Deployment finished successfully!"
