name: Python Continuous Integration on Ubuntu

# Define when the workflow should run
on:
  # Run on every push to the main branch
  push:
    branches: [ main ]
  # Run on every pull request targeting the main branch
  pull_request:
    branches: [ main ]

# Define the jobs to be executed
jobs:
  test_and_build:
    # --- THIS LINE SPECIFIES THE UBUNTU RUNNER ---
    runs-on: ubuntu-latest
    
    # Define the sequence of steps
    steps:
      # 1. Download your code from the repository
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
        
      # 2. Set up the Python environment
      - name: 2. Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          # You can change '3.11' to any version you need (e.g., '3.12')
          python-version: '3.11'
          
      # 3. Install dependencies (Crucial step for installing Pytest)
      - name: 3. Install Pytest and dependencies
        run: |
          # Ensure pip is up-to-date
          python -m pip install --upgrade pip
          # Install Pytest. If you have a requirements.txt, use: pip install -r requirements.txt
          pip install pytest
          
      # 4. Run the test suite
      - name: 4. Run tests with Pytest
        # This command executes on the Ubuntu machine
        run: pytest
        
      # 5. (Optional) Example of running a simple shell command on Ubuntu
      - name: 5. Verify Ubuntu environment
        run: |
          echo "Current OS is:"
          cat /etc/os-release
          echo "Tests completed successfully on Ubuntu."
