name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_job:
    # Use the default label: self-hosted
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Pytest
        run: pip install pytest
          
      - name: Run tests
        run: pytest

  deploy_job:
    needs: test_job
    # Use the default label: self-hosted
    runs-on: self-hosted
    
    steps:
      - name: Deployment Script
        run: |
          echo "Deployment script is running directly on your Ubuntu VPS!"
          # Add your deployment commands here
          echo "Deployment finished."
